# import = [ "~/.config/alacritty/themes/cobalt2.toml" ]

[window]
padding = { x = 3, y = 3 }
decorations = "Full"
opacity = 1.0
blur = false
resize_increments = false

[font]
normal = { family = "Operator Mono", style = "Book" }
size = 14

